name: run
channels:
  - bioconda
  - conda-forge
dependencies:
  - samtools=1.15.1
  - libzlib=1.2.11
  - python=3.8
  - biopython=1.78
  - blast=2.12.0
  - pandas=1.4.2
  - bedtools=2.30
  - primer3=2.5.0
  - clustalo
  - matplotlib
  - seaborn
  - ipykernel
  - exonerate=2.4
